include: package:flutter_lints/flutter_lints.yaml

analyzer:
  exclude:
    - build/**
    - lib/generated/**
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
  errors:
    missing_return: error
    dead_code: warning
    unused_import: error

linter:
  rules:
    # Style and organization
    always_use_package_imports: true
    always_declare_return_types: true
    avoid_print: true
    avoid_unnecessary_containers: true
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    prefer_final_fields: true
    prefer_final_locals: true
    unnecessary_this: true
    use_full_hex_values_for_flutter_colors: true
    avoid_redundant_argument_values: true

    # Best practices for null-safety and logic
    unawaited_futures: warn
    avoid_bool_literals_in_conditional_expressions: true
    avoid_dynamic_calls: true
    avoid_function_literals_in_foreach_calls: true
    avoid_nullable_type_in_catch_clause: true
    null_check_on_nullable_type_parameter: true

    # Security and maintenance
    cancel_subscriptions: true
    close_sinks: true

    # Readability
    sort_pub_dependencies: true
    curly_braces_in_flow_control_structures: true
    lines_longer_than_80_chars: false
    require_trailing_commas: true
    # Import organization
    directives_ordering: true
    prefer_relative_imports: false

    # arch and best practices
    avoid_classes_with_only_static_members: true
    avoid_multiple_declarations_per_line: true
    avoid_private_typedef_functions: true
    use_build_context_synchronously: true